name: Bug Report
description: Report a problem or error in the system
title: "Bug: [BRIEF DESCRIPTION]"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        
        Please provide detailed information about the problem you encountered in the Mergington High School activities system.
        
        **Note:** Please check if this issue has already been reported before creating a new one.

  - type: textarea
    id: bug-description
    attributes:
      label: "Describe the Bug *"
      description: "A clear and concise description of what the bug is"
      placeholder: "e.g., When I try to register for an activity, the registration button doesn't work"
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce *"
      description: "Detailed steps to reproduce the behavior"
      placeholder: |
        1. Go to the activities page
        2. Click on 'Programming Class'
        3. Click 'Register' button
        4. See error
      value: |
        1. 
        2. 
        3. 
        4. 
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: "Expected Behavior *"
      description: "What you expected to happen"
      placeholder: "e.g., The registration modal should open and allow me to enter my email"
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: "Actual Behavior *"
      description: "What actually happened instead"
      placeholder: "e.g., Nothing happens when I click the register button, or I get an error message"
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: "User Type *"
      description: "Were you using the system as a student or teacher when this happened?"
      options:
        - "Student"
        - "Teacher"
        - "Not logged in"
    validations:
      required: true

  - type: dropdown
    id: browser
    attributes:
      label: "Browser *"
      description: "Which web browser were you using?"
      options:
        - "Chrome"
        - "Firefox" 
        - "Safari"
        - "Edge"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: device-type
    attributes:
      label: "Device Type *"
      description: "What type of device were you using?"
      options:
        - "Desktop computer"
        - "Laptop"
        - "Tablet"
        - "Mobile phone"
    validations:
      required: true

  - type: textarea
    id: error-messages
    attributes:
      label: "Error Messages"
      description: "If you saw any error messages, please copy them here exactly as they appeared"
      placeholder: "Copy and paste any error messages you saw"

  - type: dropdown
    id: frequency
    attributes:
      label: "How often does this happen?"
      description: "Does this bug occur every time or just sometimes?"
      options:
        - "Every time"
        - "Most of the time"
        - "Sometimes"
        - "Only happened once"

  - type: textarea
    id: workaround
    attributes:
      label: "Workaround"
      description: "Have you found any way to work around this problem?"
      placeholder: "e.g., Refreshing the page makes it work, or using a different browser"

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any other details that might be helpful for fixing this bug"

  - type: markdown
    attributes:
      value: |
        ---
        
        ### Acceptance Criteria
        
        For the development team, this bug will be considered fixed when:
        - The reported problem no longer occurs when following the reproduction steps
        - The system behaves as expected in the described scenario
        - The fix doesn't introduce new problems or break existing functionality
        - The solution works across different browsers and device types (as applicable)
        
        ### Investigation Areas
        
        Common areas to check based on bug type:
        - **Registration issues**: Check `src/static/app.js` signup functions and `src/backend/routers/activities.py`
        - **Login problems**: Check `src/static/app.js` authentication and `src/backend/routers/auth.py`
        - **Display issues**: Check `src/static/styles.css` and `src/static/index.html`
        - **Data problems**: Check `src/backend/database.py` and data initialization
        - **API errors**: Check FastAPI endpoints and error handling
        
        ### Debugging Tips
        
        - Check browser developer console for JavaScript errors
        - Verify API responses using browser network tab or `/docs` endpoint
        - Test with different user accounts and activity states
        - Confirm issue exists with fresh browser session/cache cleared